# Nome da aplicação
spring.application.name=SecureLoginPUC

# Credenciais de teste em memória
app.user.username=joao
app.user.password=4321
app.admin.username=admin
app.admin.password=1234

# Configurações do Java Mail Sender (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diegoportella1610@gmail.com
spring.mail.password=ggocfychsbuubxpw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true